<a href="https://colab.research.google.com/github/cymyung/data-science/blob/teamlab-numpy-pandas/1_numpy_ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### numpy 모듈의 호출

In [ ]:
import numpy as np

#### array의 생성

In [ ]:
test_array = np.array(["1", "4", 5, 8], float)
test_array

array([ 1.,  4.,  5.,  8.])

In [ ]:
type(test_array[3])

numpy.float64

In [ ]:
test_array = np.array([1, 4, 5, "8"], float) # String Type의 데이터를 입력해도
test_array

array([ 1.,  4.,  5.,  8.])

In [ ]:
type(test_array[3])   # Float Type으로 자동 형변환을 실시

numpy.float64

In [ ]:
test_array.dtype   # Array(배열) 전체의 데이터 Type을 반환함

dtype('float64')

In [ ]:
test_array

array([ 1.,  4.,  5.,  8.])

In [ ]:
test_array.shape   # Array(배열) 의 shape을 반환함

(4,)

#### arrary shape

In [ ]:
vector  = [1,2,3,4]
np.array(vector, int).shape

(4,)

In [ ]:
matrix  = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [ ]:
tensor  = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [ ]:
np.array(tensor, int).ndim

3

In [ ]:
np.array(tensor, int).size

48

#### numpy dtype

In [ ]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], dtype=int)

dtype('int64')

In [ ]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32)

array([[ 1. ,  2. ,  3. ],
       [ 4.5,  5. ,  6. ]], dtype=float32)

In [ ]:
np.array([[1, 2, 3], [4.5, "5", "6"]],
         dtype=np.float32).nbytes

24

In [ ]:
np.array([[1, 2, 3], [4.5, "5", "6"]],
         dtype=np.int8).nbytes

6

In [ ]:
np.array([[1, 2, 3], [4.5, "5", "6"]],
         dtype=np.float64).nbytes

48