<a href="https://colab.research.google.com/github/cymyung/data-science/blob/main/numpy_study2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
test_array = np.array([1,4,'5','8'],float)
test_array

In [ ]:
type(test_array)

In [ ]:
type(test_array[3]) #string type을 입력해도 float type으로 자동형변환

In [ ]:
test_array.dtype

In [ ]:
test_array.ndim

In [ ]:
test_array.shape

In [ ]:
test_array.size

In [ ]:
vector = [1,2,3,4]

In [ ]:
type(vector)

In [ ]:
vector1=np.array(vector,float)

In [ ]:
type(vector1)

numpy.ndarray

In [ ]:
vector1.shape

(4,)

In [ ]:
vector1.ndim

1

In [ ]:
matrix = np.array([vector1,vector1,vector1])

In [ ]:
matrix

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
matrix.ndim

In [ ]:
matrix.size

In [ ]:
matrix.shape

In [ ]:
tensor = np.array([matrix,matrix,matrix],int)

In [ ]:
tensor

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.dtype

dtype('int64')

In [ ]:
tensor.size

36

In [ ]:
tensor.shape

(3, 3, 4)

#numpy 2

In [ ]:
tensor

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [ ]:
tensor.size

36

In [ ]:
tensor.reshape(6,6)

array([[1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 4]])

In [ ]:
tensor

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [ ]:
matrix

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
matrix.reshape(-1,1).shape

(12, 1)

In [ ]:
tensor.reshape(-1,3,3)

array([[[1, 2, 3],
        [4, 1, 2],
        [3, 4, 1]],

       [[2, 3, 4],
        [1, 2, 3],
        [4, 1, 2]],

       [[3, 4, 1],
        [2, 3, 4],
        [1, 2, 3]],

       [[4, 1, 2],
        [3, 4, 1],
        [2, 3, 4]]])

In [ ]:
tensor.flatten()

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2,
       3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [ ]:
tensor.flatten

<function ndarray.flatten>

#numpy 3

In [ ]:
matrix

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
matrix = np.array([matrix,matrix])

In [ ]:
matrix = np.vstack([matrix,matrix])

In [ ]:
matrix

array([[[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]],

       [[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]],

       [[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]],

       [[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]]])

In [ ]:
matrix.shape

(4, 3, 4)

In [ ]:
matrix[1][1][1]

2.0

In [ ]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(10,k=2)

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.random.uniform(0,10,100)

array([9.66837077, 4.37731163, 5.16763215, 5.90994918, 1.83850211,
       7.34576637, 6.87397744, 0.28530968, 7.61459064, 0.32649512,
       2.33852077, 8.87740435, 1.18063517, 4.03860457, 4.99197455,
       0.94275717, 7.6496392 , 0.24203814, 4.09505917, 1.12553894,
       0.51163011, 1.77936119, 2.93798414, 3.56895324, 9.87353722,
       9.80535146, 1.02524051, 5.12339041, 4.31609893, 0.12175348,
       7.91542007, 5.44256364, 9.52916225, 0.64394465, 2.15533066,
       7.31230128, 1.26947348, 5.31573841, 6.25267353, 3.60514437,
       4.37331967, 1.31815107, 5.66423275, 3.61019374, 0.67761039,
       6.73517206, 6.83852587, 2.58719933, 9.71862682, 7.32673139,
       7.23205846, 5.50883586, 1.17473782, 9.56715829, 0.70399833,
       4.59105757, 8.36061786, 9.36948243, 2.63745147, 7.04187453,
       3.90643955, 7.58536979, 6.62167928, 3.40315418, 4.02866546,
       7.34881846, 0.06244135, 0.24462464, 7.98574212, 4.98296402,
       9.41253607, 1.32273323, 0.6144074 , 4.46086454, 0.19577

In [ ]:
np.random.normal(80,10,10)

array([88.82140599, 85.84949642, 90.62271846, 82.65483274, 80.2974901 ,
       86.8697264 , 72.54551406, 93.51007236, 60.75666515, 74.14648813])

In [ ]:
test_a = np.array([[1,2,3],
                   [6,7,8],
                   [3,7,5]],np.float16)


In [ ]:
test_a

array([[1., 2., 3.],
       [6., 7., 8.],
       [3., 7., 5.]], dtype=float16)

In [ ]:
test_a*test_a

array([[ 1.,  4.,  9.],
       [36., 49., 64.],
       [ 9., 49., 25.]], dtype=float16)

In [4]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [7]:
np.arange(40).reshape(8,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [9]:
np.zeros(shape = (5,5),dtype=np.int16)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

In [10]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones(shape=(6,5),dtype=np.int16)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [13]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.empty((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
empty_array = np.empty((2, 2))
print("Empty Array:")
print(empty_array)

# np.zeros 예제
zeros_array = np.zeros((2, 2))
print("\nZeros Array:")
print(zeros_array)

Empty Array:
[[4.98847233e-310 0.00000000e+000]
 [4.98793184e-310 5.70151755e-321]]

Zeros Array:
[[0. 0.]
 [0. 0.]]


In [17]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [19]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
test_array = np.arange(1,11)
test_array
test_array.sum()

In [24]:
test_array1 = test_array.reshape(5,2)

In [25]:
test_array1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [26]:
test_array1.sum()

55

In [29]:
test_array1.ndim

2

In [31]:
test_array1.sum(axis=1), test_array1.sum(axis=0)

(array([ 3,  7, 11, 15, 19]), array([25, 30]))

In [33]:
test_array2 = np.array([test_array1,test_array1,test_array1])

In [34]:
test_array2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]])

In [36]:
test_array3 = np.hstack([test_array1,test_array1,test_array1])

In [37]:
test_array3

array([[ 1,  2,  1,  2,  1,  2],
       [ 3,  4,  3,  4,  3,  4],
       [ 5,  6,  5,  6,  5,  6],
       [ 7,  8,  7,  8,  7,  8],
       [ 9, 10,  9, 10,  9, 10]])

In [38]:
test_array4 = np.vstack([test_array1,test_array1,test_array1])

In [39]:
test_array4

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [41]:
test_array2.ndim

3

In [45]:
test_a = np.array([[1,2,3],
                   [4,6,7]],np.float16)

In [46]:
test_a

array([[1., 2., 3.],
       [4., 6., 7.]], dtype=float16)

In [47]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 12., 14.]], dtype=float16)

In [48]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 36., 49.]], dtype=float16)

In [49]:
matrix_a = np.arange(1,13).reshape(3,4)

In [50]:
matrix_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [52]:
test_a,test_b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]]))

In [55]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [56]:
test_b.dot(test_a)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

In [58]:
test_a.dot(test_b).sum(),test_b.dot(test_a).sum()

(415, 612)

In [60]:
test_a, test_a.T, test_a.transpose()

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

# Broadcasting

In [61]:
test_a,test_b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]]))

In [62]:
scalar = 5

In [63]:
test_a + scalar

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [64]:
test_b - 3

array([[4, 5],
       [6, 7],
       [8, 9]])

In [65]:
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
vector

NameError: name 'vector' is not defined

In [67]:
vector = [3,4,5]

In [68]:
test_a + vector

array([[ 4,  6,  8],
       [ 7,  9, 11]])

In [69]:
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

iternation_max = 100000000

vector = list(range(iternation_max))
scalar = 2

%timeit sclar_vector_product(scalar, vector) # for loop을 이용한 성능

KeyboardInterrupt: 

In [ ]:
%timeit [scalar * value for value in range(iternation_max)] # list comprehension을 이용한 성능
%timeit np.arange(iternation_max) * scalar # numpy를 이용한 성능

In [70]:
a = np.arange(1,10)

In [71]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [79]:
np.all(a<9)

False

In [80]:
test_a = np.array([1,3,0],float)
test_b = np.array([5,2,1],float)
test_a > test_b

array([False,  True, False])

In [81]:
test_a == test_b

array([False, False, False])

In [83]:
(test_a > test_b).all()

False

In [85]:
a = np.array([1,3,0],float)
np.logical_and(a>0, a<3)

array([ True, False, False])

In [86]:
np.logical_not(a == 3)

array([ True, False,  True])

In [100]:
a = np.array([10,30,90])
a

array([10, 30, 90])

In [102]:
np.where(a>1)

(array([0, 1, 2]),)

In [111]:
np.where(a>15,"yes",'no') # excel의 if 함수와 같다.

array(['no', 'yes', 'yes'], dtype='<U3')

In [122]:
b = np.arange(14,23)

array([17, 18, 19, 20, 21, 22])

In [123]:
b[np.where(b > 16)]

array([17, 18, 19, 20, 21, 22])

In [126]:
b.argmin()

0

In [133]:
test_array = np.array([1,4,0,2,3,8,7,9,3,11,15,3],float)

In [128]:
test_array>3

array([False,  True, False, False, False,  True,  True,  True])

In [134]:
test_array[test_array>4]

array([ 8.,  7.,  9., 11., 15.])

In [141]:
a=np.array(np.random.randint(8,15,100).reshape(10,10))

In [142]:
a

array([[13, 14, 12, 14, 12, 11, 14, 14, 14,  9],
       [ 8, 12, 11, 10, 10, 10, 13, 14, 13, 12],
       [14, 14, 13,  8, 10, 12, 11, 11, 13, 11],
       [14, 11, 10, 10, 12, 14,  8, 10,  8, 11],
       [ 8, 12, 12,  9,  8, 10, 12, 10,  8,  8],
       [10, 10, 10, 14, 14, 10, 10, 10,  8, 14],
       [10, 14, 13, 11, 14,  8, 11, 12, 11, 14],
       [11, 12, 14,  8, 13, 11, 10, 12,  8,  9],
       [11,  8, 11,  9, 12, 10, 12, 13,  8, 14],
       [ 8, 13, 10, 11, 13, 12, 11, 11, 14, 11]])

In [146]:
b = a < 13

In [148]:
b.astype(np.int)

<ipython-input-148-f87baa30f6af>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b.astype(np.int)


array([[0, 0, 1, 0, 1, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 0, 1],
       [0, 1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 1, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1, 1, 1, 1, 0],
       [1, 1, 0, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 0],
       [1, 0, 1, 1, 0, 1, 1, 1, 0, 1]])

In [150]:
a[b]

array([12, 12, 11,  9,  8, 12, 11, 10, 10, 10, 12,  8, 10, 12, 11, 11, 11,
       11, 10, 10, 12,  8, 10,  8, 11,  8, 12, 12,  9,  8, 10, 12, 10,  8,
        8, 10, 10, 10, 10, 10, 10,  8, 10, 11,  8, 11, 12, 11, 11, 12,  8,
       11, 10, 12,  8,  9, 11,  8, 11,  9, 12, 10, 12,  8,  8, 10, 11, 12,
       11, 11, 11])

In [151]:
a[b].size

71