<a href="https://colab.research.google.com/github/cymyung/data-science/blob/main/numpystudy_240122.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.shape
a.dtype.name
a.itemsize
a.size

(3, 5)

In [ ]:
type(a)

numpy.ndarray

In [ ]:
b = np.array([6,7,8])

In [ ]:
b

array([6, 7, 8])

In [ ]:
a = np.array([[1,2],
             [1,2]])
b = np.identity(2)

In [ ]:
a,b

(array([[1, 2],
        [1, 2]]),
 array([[1., 0.],
        [0., 1.]]))

In [ ]:
a * b, a @ b

(array([[1., 0.],
        [0., 2.]]),
 array([[1., 2.],
        [1., 2.]]))

In [ ]:
rg = np.random.default_rng(1)

In [ ]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = rg.random((2,3))
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [ ]:
a * 3

array([[3., 3., 3.],
       [3., 3., 3.]])

In [ ]:
b += a

In [ ]:
b

array([[1.51182162, 1.9504637 , 1.14415961],
       [1.94864945, 1.31183145, 1.42332645]])

In [ ]:
a = np.ones(3, dtype = np.int32)

In [ ]:
pi = 3.14
b = np.linspace(0,pi,3)

In [ ]:
b

array([0.  , 1.57, 3.14])

In [ ]:
b.dtype.name

'float64'

In [ ]:
c = a + b

In [ ]:
c

array([1.  , 2.57, 4.14])

In [ ]:
d = np.exp(c * 1j)

In [ ]:
d

array([ 0.54030231+0.84147098j, -0.84104046+0.54097222j,
       -0.54164179-0.8406094j ])

In [ ]:
d.dtype.name

'complex128'

In [ ]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b.sum(axis = 0)

array([12, 15, 18, 21])

In [ ]:
b.cumsum(axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [ ]:
a = np.arange(10) ** 3

In [ ]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
a[2]

8

In [ ]:
a[:6:2]

array([ 0,  8, 64])

In [ ]:
def f(x,y):
    return 10 * x + y

In [ ]:
b = np.fromfunction(f,(5,4))

In [ ]:
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [ ]:
c = np.array([[[0,1,2],
               [11,12,13]],
              [[100,111,112],
               [232,242,256]]])
c

array([[[  0,   1,   2],
        [ 11,  12,  13]],

       [[100, 111, 112],
        [232, 242, 256]]])

In [ ]:
c.shape

(2, 2, 3)

In [ ]:
c.size

12

In [ ]:
c[1,...]

array([[100, 111, 112],
       [232, 242, 256]])

In [ ]:
c[:,1,:]

array([[ 11,  12,  13],
       [232, 242, 256]])

In [ ]:
c[...,1]

array([[  1,  12],
       [111, 242]])

In [ ]:
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [ ]:
for row in b:
    print(row)

[0. 1. 2. 3.]
[10. 11. 12. 13.]
[20. 21. 22. 23.]
[30. 31. 32. 33.]
[40. 41. 42. 43.]


In [ ]:
d = list(b.flat)

In [ ]:
print(d)

[0.0, 1.0, 2.0, 3.0, 10.0, 11.0, 12.0, 13.0, 20.0, 21.0, 22.0, 23.0, 30.0, 31.0, 32.0, 33.0, 40.0, 41.0, 42.0, 43.0]


In [ ]:
d


[0.0,
 1.0,
 2.0,
 3.0,
 10.0,
 11.0,
 12.0,
 13.0,
 20.0,
 21.0,
 22.0,
 23.0,
 30.0,
 31.0,
 32.0,
 33.0,
 40.0,
 41.0,
 42.0,
 43.0]

In [ ]:
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [ ]:
b.ravel()

array([ 0.,  1.,  2.,  3., 10., 11., 12., 13., 20., 21., 22., 23., 30.,
       31., 32., 33., 40., 41., 42., 43.])

In [ ]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [ ]:
b.reshape(4,5)

array([[ 0.,  1.,  2.,  3., 10.],
       [11., 12., 13., 20., 21.],
       [22., 23., 30., 31., 32.],
       [33., 40., 41., 42., 43.]])

In [ ]:
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [ ]:
rg = np.random.default_rng(1)

In [ ]:
a = np.floor(10 * rg.random((2,2)))
a

array([[5., 9.],
       [1., 9.]])

In [ ]:
rg = np.random.default_rng(1)

In [ ]:
a = np.floor(10 * rg.random([2,2]))

In [ ]:
b = np.floor(10 * rg.random([2,2]))

In [ ]:
a,b

(array([[1., 4.],
        [2., 2.]]),
 array([[7., 2.],
        [4., 9.]]))

In [ ]:
np.vstack([a,b])

array([[1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [ ]:
np.hstack([a,b])

array([[1., 4., 7., 2.],
       [2., 2., 4., 9.]])

In [ ]:
np.column_stack((a,b))

array([[1., 4., 7., 2.],
       [2., 2., 4., 9.]])

In [ ]:
np.row_stack((a,b)).newaxis

AttributeError: 'numpy.ndarray' object has no attribute 'newaxis'

In [ ]:
from numpy import newaxis

In [ ]:
a

array([[1., 4.],
       [2., 2.]])

In [ ]:
a.newaxis

AttributeError: 'numpy.ndarray' object has no attribute 'newaxis'

In [ ]:
a1 = np.array([1,4,5])

In [ ]:
a1

array([1, 4, 5])

In [ ]:
a1.newaxis

AttributeError: 'numpy.ndarray' object has no attribute 'newaxis'

In [ ]:
a1[:,newaxis]

TypeError: list indices must be integers or slices, not tuple

In [ ]:
a = np.floor(10 * rg.random((2,12)))
a

array([[9., 7., 5., 2., 1., 9., 5., 1., 6., 7., 6., 9.],
       [0., 5., 4., 0., 6., 8., 5., 2., 8., 5., 5., 7.]])

In [ ]:
np.hsplit(a,3)

[array([[9., 7., 5., 2.],
        [0., 5., 4., 0.]]),
 array([[1., 9., 5., 1.],
        [6., 8., 5., 2.]]),
 array([[6., 7., 6., 9.],
        [8., 5., 5., 7.]])]

In [ ]:
np.hsplit(a,(3,4,5))

[array([[9., 7., 5.],
        [0., 5., 4.]]),
 array([[2.],
        [0.]]),
 array([[1.],
        [6.]]),
 array([[9., 5., 1., 6., 7., 6., 9.],
        [8., 5., 2., 8., 5., 5., 7.]])]

In [ ]:
np.vsplit(a,2)

[array([[9., 7., 5., 2., 1., 9., 5., 1., 6., 7., 6., 9.]]),
 array([[0., 5., 4., 0., 6., 8., 5., 2., 8., 5., 5., 7.]])]

In [ ]:
a

array([[9., 7., 5., 2., 1., 9., 5., 1., 6., 7., 6., 9.],
       [0., 5., 4., 0., 6., 8., 5., 2., 8., 5., 5., 7.]])

In [ ]:
b

array([[7., 2.],
       [4., 9.]])

In [ ]:
c

array([[[  0,   1,   2],
        [ 11,  12,  13]],

       [[100, 111, 112],
        [232, 242, 256]]])

In [ ]:
c1 = c.view()

In [ ]:
c1

array([[[  0,   1,   2],
        [ 11,  12,  13]],

       [[100, 111, 112],
        [232, 242, 256]]])

In [ ]:
id(c),id(c1)

(132381231746672, 132381231744176)

In [ ]:
c[0,0,0] = 999

In [ ]:
c

array([[[999,   1,   2],
        [ 11,  12,  13]],

       [[100, 111, 112],
        [232, 242, 256]]])

In [ ]:
c1

array([[[999,   1,   2],
        [ 11,  12,  13]],

       [[100, 111, 112],
        [232, 242, 256]]])

In [ ]:
c is c1

False

In [ ]:
c1.base is c

True

In [ ]:
c.base is c1

False

In [ ]:
c1[0,0,0] = 888

In [ ]:
c1

array([[[888,   1,   2],
        [ 11,  12,  13]],

       [[100, 111, 112],
        [232, 242, 256]]])

In [ ]:
c

array([[[888,   1,   2],
        [ 11,  12,  13]],

       [[100, 111, 112],
        [232, 242, 256]]])

In [ ]:
type(s)

int

In [ ]:
s = c[:, 1,1:3]

In [ ]:
s

array([[ 12,  13],
       [242, 256]])

In [ ]:
type(s)

numpy.ndarray

In [ ]:
s[:,:] = 1234

In [ ]:
c

array([[[ 888,    1,    2],
        [  11, 1234, 1234]],

       [[ 100,  111,  112],
        [ 232, 1234, 1234]]])

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6])

In [8]:
a.shape,type(a)

((6,), numpy.ndarray)

In [5]:
a2 = a[np.newaxis, :]

In [6]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [9]:
a2.shape,type(a2)

((1, 6), numpy.ndarray)

In [12]:
a3 = a[:, np.newaxis]

In [13]:
a3,a3.shape

(array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]),
 (6, 1))

In [20]:
a22 = a2[np.newaxis, :]

In [15]:
a2, a22

(array([[1, 2, 3, 4, 5, 6]]), array([[[1, 2, 3, 4, 5, 6]]]))

In [16]:
a22.shape

(1, 1, 6)

In [21]:
a23 = a2[:,np.newaxis]

In [18]:
a23

array([[[1, 2, 3, 4, 5, 6]]])

In [24]:
a31 = a3[:,np.newaxis]
a32 = a3[np.newaxis,:]

In [25]:
a31,a32

(array([[[1]],
 
        [[2]],
 
        [[3]],
 
        [[4]],
 
        [[5]],
 
        [[6]]]),
 array([[[1],
         [2],
         [3],
         [4],
         [5],
         [6]]]))

In [30]:
a31.shape, a32.shape

((6, 1, 1), (1, 6, 1))

(1, 6, 1)

In [33]:
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

In [34]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
a[(5 < a) & (a < 9)]

array([6, 7, 8])

In [48]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [49]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
b = np.nonzero(a<10)

In [53]:
b

(array([0, 0, 0, 0, 1, 1, 1, 1, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0]))

In [54]:
coord = list(zip(b[0],b[1]))
for co in coord:
    print(co)

(0, 0)
(0, 1)
(0, 2)
(0, 3)
(1, 0)
(1, 1)
(1, 2)
(1, 3)
(2, 0)


In [55]:
a[b]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a,b

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 (array([0, 0, 0, 0, 1, 1, 1, 1, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0])))

In [57]:
x = np.arange(1,25).reshape(2,-1)

In [58]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [59]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [60]:
x.reshape(3,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [64]:
np.hsplit(x.reshape(3,-1),(3,4,7))

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19]]),
 array([[ 4],
        [12],
        [20]]),
 array([[ 5,  6,  7],
        [13, 14, 15],
        [21, 22, 23]]),
 array([[ 8],
        [16],
        [24]])]

In [71]:
a = np.arange(1,13).reshape(3,-1)

In [72]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
b1 = a[0,:]

In [74]:
b1

array([1, 2, 3, 4])

In [75]:
b1[0] = 99

In [76]:
b1

array([99,  2,  3,  4])

In [77]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
b2 = a.copy()

In [79]:
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
b2[0,0] = 88

In [82]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
b2

array([[88,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
np.random.rand(3)

array([0.42745657, 0.4599841 , 0.90918159])

In [90]:
rg = np.random.default_rng(seed=49)

In [95]:
rg.random(3)

array([0.37224908, 0.71865929, 0.9334943 ])

In [105]:
c1=rg.integers(10, size = [5,9])

In [106]:
c1

array([[9, 2, 7, 1, 6, 8, 6, 4, 1],
       [1, 5, 5, 9, 2, 5, 4, 2, 9],
       [2, 2, 7, 1, 3, 9, 8, 9, 8],
       [7, 2, 8, 6, 7, 3, 6, 9, 7],
       [2, 1, 9, 5, 4, 2, 6, 4, 4]])

In [108]:
type(c1)

numpy.ndarray

In [111]:
np.unique(c1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
a = np.array([11,11,12,13,13,14,15,15,15,16,17,18,18,19,20])

In [113]:
unique_value = np.unique(a)

In [114]:
unique_value

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [115]:
indices_list = np.unique(a, return_index = True)

In [117]:
indices_list

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  5,  6,  9, 10, 11, 13, 14]))

In [118]:
unique_value, indices_list = np.unique(a, return_index = True)

In [120]:
print(indices_list)

[ 0  2  3  5  6  9 10 11 13 14]


In [122]:
ocurrence_list = np.unique(a, return_counts = True)

In [126]:
ocurrence_list

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([2, 1, 2, 1, 3, 1, 1, 2, 1, 1]))

In [127]:
c1

array([[9, 2, 7, 1, 6, 8, 6, 4, 1],
       [1, 5, 5, 9, 2, 5, 4, 2, 9],
       [2, 2, 7, 1, 3, 9, 8, 9, 8],
       [7, 2, 8, 6, 7, 3, 6, 9, 7],
       [2, 1, 9, 5, 4, 2, 6, 4, 4]])

In [129]:
np.unique(c1,axis = 0)

array([[1, 5, 5, 9, 2, 5, 4, 2, 9],
       [2, 1, 9, 5, 4, 2, 6, 4, 4],
       [2, 2, 7, 1, 3, 9, 8, 9, 8],
       [7, 2, 8, 6, 7, 3, 6, 9, 7],
       [9, 2, 7, 1, 6, 8, 6, 4, 1]])

In [130]:
np.unique(c1,axis = 1)

array([[1, 1, 2, 4, 6, 6, 7, 8, 9],
       [9, 9, 5, 2, 2, 4, 5, 5, 1],
       [1, 8, 2, 9, 3, 8, 7, 9, 2],
       [6, 7, 2, 9, 7, 6, 8, 3, 7],
       [5, 4, 1, 4, 4, 6, 9, 2, 2]])

In [139]:
d1 = [[1,1,3,4],
      [1,1,3,4],
      [5,7,5,8]]

In [132]:
d1

[[1, 2, 3, 4], [1, 2, 3, 4], [5, 6, 7, 8]]

In [140]:
np.unique(d1,axis = 1)

array([[1, 1, 3, 4],
       [1, 1, 3, 4],
       [5, 7, 5, 8]])

In [141]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [142]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [143]:
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [144]:
np.flip(arr_2d, axis = 0), np.flip(arr_2d, axis = 1)

(array([[ 9, 10, 11, 12],
        [ 5,  6,  7,  8],
        [ 1,  2,  3,  4]]),
 array([[ 4,  3,  2,  1],
        [ 8,  7,  6,  5],
        [12, 11, 10,  9]]))

In [150]:
arr_2d[1] = np.flip(arr_2d[1])
arr_2d

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [157]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [165]:
arr_2d[:,1]= np.flip(arr_2d[:,1])

In [167]:
arr_2d

array([[ 1, 10,  3,  4],
       [ 8,  7,  6,  5],
       [ 9,  2, 11, 12]])

In [168]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [175]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [176]:
arr_2d[:,0]= np.flip(arr_2d[:,0])

In [177]:
arr_2d

array([[ 9,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 1, 10, 11, 12]])