<a href="https://colab.research.google.com/github/cymyung/data-science/blob/main/numpystudy_240122.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape
a.dtype.name
a.itemsize
a.size

(3, 5)

In [7]:
type(a)

numpy.ndarray

In [8]:
b = np.array([6,7,8])

In [9]:
b

array([6, 7, 8])

In [10]:
a = np.array([[1,2],
             [1,2]])
b = np.identity(2)

In [11]:
a,b

(array([[1, 2],
        [1, 2]]),
 array([[1., 0.],
        [0., 1.]]))

In [12]:
a * b, a @ b

(array([[1., 0.],
        [0., 2.]]),
 array([[1., 2.],
        [1., 2.]]))

In [13]:
rg = np.random.default_rng(1)

In [19]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
b = rg.random((2,3))
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [21]:
a * 3

array([[3., 3., 3.],
       [3., 3., 3.]])

In [22]:
b += a

In [23]:
b

array([[1.51182162, 1.9504637 , 1.14415961],
       [1.94864945, 1.31183145, 1.42332645]])

In [33]:
a = np.ones(3, dtype = np.int32)

In [30]:
pi = 3.14
b = np.linspace(0,pi,3)

In [31]:
b

array([0.  , 1.57, 3.14])

In [32]:
b.dtype.name

'float64'

In [34]:
c = a + b

In [35]:
c

array([1.  , 2.57, 4.14])

In [36]:
d = np.exp(c * 1j)

In [37]:
d

array([ 0.54030231+0.84147098j, -0.84104046+0.54097222j,
       -0.54164179-0.8406094j ])

In [39]:
d.dtype.name

'complex128'

In [40]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
b.sum(axis = 0)

array([12, 15, 18, 21])

In [44]:
b.cumsum(axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [45]:
a = np.arange(10) ** 3

In [46]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [47]:
a[2]

8

In [48]:
a[:6:2]

array([ 0,  8, 64])

In [49]:
def f(x,y):
    return 10 * x + y

In [51]:
b = np.fromfunction(f,(5,4))

In [52]:
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [53]:
c = np.array([[[0,1,2],
               [11,12,13]],
              [[100,111,112],
               [232,242,256]]])
c

array([[[  0,   1,   2],
        [ 11,  12,  13]],

       [[100, 111, 112],
        [232, 242, 256]]])

In [54]:
c.shape

(2, 2, 3)

In [55]:
c.size

12

In [56]:
c[1,...]

array([[100, 111, 112],
       [232, 242, 256]])

In [58]:
c[:,1,:]

array([[ 11,  12,  13],
       [232, 242, 256]])

In [59]:
c[...,1]

array([[  1,  12],
       [111, 242]])

In [60]:
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [61]:
for row in b:
    print(row)

[0. 1. 2. 3.]
[10. 11. 12. 13.]
[20. 21. 22. 23.]
[30. 31. 32. 33.]
[40. 41. 42. 43.]


In [70]:
d = list(b.flat)

In [71]:
print(d)

[0.0, 1.0, 2.0, 3.0, 10.0, 11.0, 12.0, 13.0, 20.0, 21.0, 22.0, 23.0, 30.0, 31.0, 32.0, 33.0, 40.0, 41.0, 42.0, 43.0]


In [72]:
d


[0.0,
 1.0,
 2.0,
 3.0,
 10.0,
 11.0,
 12.0,
 13.0,
 20.0,
 21.0,
 22.0,
 23.0,
 30.0,
 31.0,
 32.0,
 33.0,
 40.0,
 41.0,
 42.0,
 43.0]

In [73]:
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [75]:
b.ravel()

array([ 0.,  1.,  2.,  3., 10., 11., 12., 13., 20., 21., 22., 23., 30.,
       31., 32., 33., 40., 41., 42., 43.])

In [76]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [77]:
type(b)

numpy.ndarray

In [78]:
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [79]:
b.reshape(4,5)

array([[ 0.,  1.,  2.,  3., 10.],
       [11., 12., 13., 20., 21.],
       [22., 23., 30., 31., 32.],
       [33., 40., 41., 42., 43.]])

In [80]:
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [81]:
rg = np.random.default_rng(1)

In [85]:
a = np.floor(10 * rg.random((2,2)))
a

array([[5., 9.],
       [1., 9.]])

In [88]:
rg = np.random.default_rng(1)

In [94]:
a = np.floor(10 * rg.random([2,2]))

In [96]:
b = np.floor(10 * rg.random([2,2]))

In [97]:
a,b

(array([[1., 4.],
        [2., 2.]]),
 array([[7., 2.],
        [4., 9.]]))

In [99]:
np.vstack([a,b])

array([[1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [100]:
np.hstack([a,b])

array([[1., 4., 7., 2.],
       [2., 2., 4., 9.]])

In [101]:
np.column_stack((a,b))

array([[1., 4., 7., 2.],
       [2., 2., 4., 9.]])

In [103]:
np.row_stack((a,b)).newaxis

AttributeError: 'numpy.ndarray' object has no attribute 'newaxis'

In [113]:
from numpy import newaxis

In [114]:
a

array([[1., 4.],
       [2., 2.]])

In [115]:
a.newaxis

AttributeError: 'numpy.ndarray' object has no attribute 'newaxis'

In [122]:
a1 = np.array([1,4,5])

In [123]:
a1

array([1, 4, 5])

In [124]:
a1.newaxis

AttributeError: 'numpy.ndarray' object has no attribute 'newaxis'

In [118]:
a1[:,newaxis]

TypeError: list indices must be integers or slices, not tuple

In [125]:
a = np.floor(10 * rg.random((2,12)))
a

array([[9., 7., 5., 2., 1., 9., 5., 1., 6., 7., 6., 9.],
       [0., 5., 4., 0., 6., 8., 5., 2., 8., 5., 5., 7.]])

In [131]:
np.hsplit(a,3)

[array([[9., 7., 5., 2.],
        [0., 5., 4., 0.]]),
 array([[1., 9., 5., 1.],
        [6., 8., 5., 2.]]),
 array([[6., 7., 6., 9.],
        [8., 5., 5., 7.]])]

In [132]:
np.hsplit(a,(3,4,5))

[array([[9., 7., 5.],
        [0., 5., 4.]]),
 array([[2.],
        [0.]]),
 array([[1.],
        [6.]]),
 array([[9., 5., 1., 6., 7., 6., 9.],
        [8., 5., 2., 8., 5., 5., 7.]])]

In [127]:
np.vsplit(a,2)

[array([[9., 7., 5., 2., 1., 9., 5., 1., 6., 7., 6., 9.]]),
 array([[0., 5., 4., 0., 6., 8., 5., 2., 8., 5., 5., 7.]])]

In [133]:
a

array([[9., 7., 5., 2., 1., 9., 5., 1., 6., 7., 6., 9.],
       [0., 5., 4., 0., 6., 8., 5., 2., 8., 5., 5., 7.]])

In [134]:
b

array([[7., 2.],
       [4., 9.]])

In [135]:
c

array([[[  0,   1,   2],
        [ 11,  12,  13]],

       [[100, 111, 112],
        [232, 242, 256]]])

In [136]:
c1 = c.view()

In [137]:
c1

array([[[  0,   1,   2],
        [ 11,  12,  13]],

       [[100, 111, 112],
        [232, 242, 256]]])

In [138]:
id(c),id(c1)

(132381231746672, 132381231744176)

In [139]:
c[0,0,0] = 999

In [140]:
c

array([[[999,   1,   2],
        [ 11,  12,  13]],

       [[100, 111, 112],
        [232, 242, 256]]])

In [141]:
c1

array([[[999,   1,   2],
        [ 11,  12,  13]],

       [[100, 111, 112],
        [232, 242, 256]]])

In [142]:
c is c1

False

In [143]:
c1.base is c

True

In [144]:
c.base is c1

False

In [145]:
c1[0,0,0] = 888

In [146]:
c1

array([[[888,   1,   2],
        [ 11,  12,  13]],

       [[100, 111, 112],
        [232, 242, 256]]])

In [147]:
c

array([[[888,   1,   2],
        [ 11,  12,  13]],

       [[100, 111, 112],
        [232, 242, 256]]])

In [159]:
type(s)

int

In [161]:
s = c[:, 1,1:3]

In [163]:
s

array([[ 12,  13],
       [242, 256]])

In [162]:
type(s)

numpy.ndarray

In [164]:
s[:,:] = 1234

In [165]:
c

array([[[ 888,    1,    2],
        [  11, 1234, 1234]],

       [[ 100,  111,  112],
        [ 232, 1234, 1234]]])